[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd presentation && npm install"]

[phases.build]
cmds = ["cd presentation && npm run build"]

[start]
cmd = "cd presentation && npm run start"
